language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

env:
  - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=freebsd GIMME_ARCH=amd64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip